// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});

export const adapter = new PrismaPg({
    connectionString: process.env['DATABASE_URL'],
});
export const prisma = new PrismaClient({
    adapter,
});
